# Generated by Django 4.0.6 on 2023-01-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
                ('location', models.CharField(max_length=20)),
                ('ceo', models.CharField(max_length=20)),
            ],
        ),
    ]
