# Generated by Django 4.0.6 on 2023-01-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comp', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('elig', models.CharField(max_length=20)),
                ('addr', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phNo', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HydJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comp', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('elig', models.CharField(max_length=20)),
                ('addr', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phNo', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PuneJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comp', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('elig', models.CharField(max_length=20)),
                ('addr', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phNo', models.BigIntegerField()),
            ],
        ),
    ]
